USE [master]
GO

/****** Object:  Database [UrunArama]    Script Date: 13.04.2022 17:38:56 ******/
CREATE DATABASE [UrunArama]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UrunArama', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\UrunArama.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UrunArama_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\UrunArama_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UrunArama].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UrunArama] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UrunArama] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UrunArama] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UrunArama] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UrunArama] SET ARITHABORT OFF 
GO

ALTER DATABASE [UrunArama] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UrunArama] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UrunArama] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UrunArama] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UrunArama] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UrunArama] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UrunArama] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UrunArama] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UrunArama] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UrunArama] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UrunArama] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UrunArama] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UrunArama] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UrunArama] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UrunArama] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UrunArama] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UrunArama] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UrunArama] SET RECOVERY FULL 
GO

ALTER DATABASE [UrunArama] SET  MULTI_USER 
GO

ALTER DATABASE [UrunArama] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UrunArama] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UrunArama] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UrunArama] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [UrunArama] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UrunArama] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [UrunArama] SET QUERY_STORE = OFF
GO

ALTER DATABASE [UrunArama] SET  READ_WRITE 
GO


